sources:
  - name: c360raw
    schema: spark_catalog.c360raw  
    tables:
      - name: cart_items
      - name: customer
      - name: product
      - name: order_items
      - name: product_rating
      - name: support_chat
  - name: c360rawjson
    schema: json
    tables:
      - name: clickstream
        identifier: 's3://{{env_var("RAW_BUCKET")}}/clickstream/'
        quoting:
         identifier: true
  - name: c360rawcsv
    schema: csv
    tables:
      - name: er_matches
        identifier: 's3://{{env_var("RAW_BUCKET")}}/er/customer/CustomerMatching/*/*/*'
        quoting:
         identifier: true