site_name: AWS Partner Network (APN) Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints:
    - Advertising & Marketing:
      - Audience and Customer Data Management: 'Advertising&Marketing/AudienceAndCustomerDataManagement/AudienceAndCustomerDataManagement.md'
      - Advertising Platforms: 'Advertising&Marketing/AdvertisingPlatforms/AdvertisingPlatforms.md'
      - Advertising Intelligence and Measurement: 'Advertising&Marketing/AdvertisingIntelligenceAndMeasurement/AdvertisingIntelligenceAndMeasurement.md'
      - Privacy Enhanced Data Collaboration: 'Advertising&Marketing/Privacy Enhanced Data Collaboration/PrivacyEnhancedDataCollaboration.md'
    - Automotive: 'Automotive/comingsoon.md'
    - Aerospace & Satelite: 'Aerospace&Satelite/comingsoon.md'
    - Consumer Goods: 'ConsumerGoods/comingsoon.md'
    - Energy & Utilities:
      - Power & Utilities: 'Energy&Utilities/Power&Utilities/Power&Utilities.md'
      - Oil and Gas: 'Energy&Utilities/Oil&Gas/Oil&Gas.md'
    - Financial Services:
      - Core Banking System Modernization:
        - EKS Blueprints (CDK): 'https://aws-quickstart.github.io/cdk-eks-blueprints/'
        - Application Modernization Blueprints: 'https://catalog.us-east-1.prod.workshops.aws/workshops/96f22c5f-744f-46a6-9a98-a8b65941f85f/en-US'
    - Healthcare & Life Sciences: 'Healthcare&LifeSciences/comingsoon.md'
    - Manufacturing & Industrial: 'Manufacturing&Industrial/comingsoon.md'
    - Media & Entertainment: 'Media&Entertainment/comingsoon.md'
    - Public Sector: 'PublicSector/comingsoon.md'
    - Retail: 'Retail/comingsoon.md'
    - Sports: 'Sports/comingsoon.md'
    - Travel & Hospitality: 'Travel&Hospitality/comingsoon.md'
    - Telecommunications: 'Telecommunications/comingsoon.md'
  - Cross-industry Accelerators: 
    - Sustainability:
      - Carbon & ESG: 'Sustainability/Carbon&ESG/Carbon&ESG.md'
      - Energy Transition: 'Sustainability/EnergyTransition/EnergyTransition.md'
      - Climate & Nature: 'Sustainability/Climate&Nature/Climate&Nature.md'
      - Sustainable Operations: 'Sustainability/SustainableOperations/SustainableOperations.md'
      - Sustainable Value Chain: 'Sustainability/SustainableValueChain/SustainableValueChain.md'
      - IT Infrastructure & Architecture: 'Sustainability/ITInfrastructure&Architecture/ITInfrastructure&Architecture.md'
    - Data & AI Cross-industry: 'comingsoon15.md'
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom