site_name: APN Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints: 
    - Advertising & Marketing:
      - Customer 360:
      - Campaigns and Journeys:
      - Customer and User Support:
      - Digital Content Creation:
      - Retail Media:
      - Agency Enablement:
      - Measurement, Attribution and Verification:
      - Consent management & data governance in AdTech:
      - Data Cleanrooms:
    - Automotive:
    - Aerospace & Satelite: 
    - Consumer Goods: 
    - Energy & Utilities:
    - Financial Services:
    - Healthcare & Life Sciences:
    - Manufacturing & Industrial:
    - Media & Entertainment:
    - Public Sector:
    - Retail:
    - Sports:
    - Travel & Hospitality:
    - Telecommunications: 
  - Cross-industry Accelerators:
    - Sustainability:
    - Data & AI Cross-industry:
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom