site_name: AWS Partner Network (APN) Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints:
    - Advertising & Marketing:
      - Customer360: 'https://github.com/aws-samples/aws-industry-blueprints-for-data-and-ai/tree/main/blueprints/datalake-warehouse-c360'
      - Campaigns and Journeys: 'https://github.com/aws-samples/communication-developer-services-reference-architectures'
      - Customer and User Support:
        - Amazon Transcribe Post Call Analytics (PCA) Solution: 'https://github.com/aws-samples/amazon-transcribe-post-call-analytics'
        - Quantiphi Real-Time Call Center Analytics: 'https://quantiphi.com/case-studies/real-time-call-center-analytics/'
        - Amazon Transcribe Live Call Analytics (LCA) with Agent Assist Sample Solution: 'https://github.com/aws-samples/amazon-transcribe-live-call-analytics'
      - Digital Content Creation:
        - Generative AI for Advertising and Marketing Industry: 'https://catalog.workshops.aws/genai-advertising-marketing/en-US'
        - Generative AI Movie Poster Generator: 'https://github.com/cloudbennett/generative-ai-sagemaker-cdk-demo/tree/main'
      - Retail Media: 'https://github.com/aws-samples/retail-demo-store'
      - Agency Enablement: 
        - Guidance for Implementing Google Privacy Sandbox Key/Value Service on AWS: 'https://aws.amazon.com/solutions/guidance/implementing-google-privacy-sandbox-key-value-service-on-aws/'
        - Guidance for Advertising Agency Planning Management on AWS: 'https://aws.amazon.com/solutions/guidance/advertising-agency-planning-management-on-aws/'
      - Measurement, Attribution and Verification: 'https://aws.amazon.com/solutions/implementations/amazon-marketing-cloud-uploader-from-aws/?did=sl_card&trk=sl_card'
      - Consent management & data governance in AdTech: 'https://catalog.us-east-1.prod.workshops.aws/workshops/1bf9302a-862c-4e21-9e45-c81fa055643b/en-US'
      - Data Cleanrooms: 'https://github.com/aws-solutions/data-connectors-for-aws-clean-rooms'
    - Automotive: 'comingsoon1.md'
    - Aerospace & Satelite: 'comingsoon2.md'
    - Consumer Goods: 'comingsoon3.md'
    - Energy & Utilities:
      - Enterprise Asset Management Maximo Application Suite on AWS: 'https://catalog.us-east-1.prod.workshops.aws/workshops/78554b88-0cd8-45a1-b9ee-2c1078aa6995/en-US'
      - Renewables Data Lake & Analytics: 'https://aws.amazon.com/energy-utilities/solutions/renewables-data-lake/'
      - Seismic Processing - Energy Data Insights on AWS - OSDU Data Platform: 'https://aws.amazon.com/energy-utilities/osdu-data-platform/'
    - Financial Services:
      - Core Banking System Modernization:
        - EKS Blueprints (CDK): 'https://aws-quickstart.github.io/cdk-eks-blueprints/'
        - Application Modernization Blueprints: 'https://catalog.us-east-1.prod.workshops.aws/workshops/96f22c5f-744f-46a6-9a98-a8b65941f85f/en-US'
    - Healthcare & Life Sciences: 'comingsoon6.md'
    - Manufacturing & Industrial: 'comingsoon7.md'
    - Media & Entertainment: 'comingsoon8.md'
    - Public Sector: 'comingsoon9.md'
    - Retail: 'comingsoon10.md'
    - Sports: 'comingsoon11.md'
    - Travel & Hospitality: 'comingsoon12.md'
    - Telecommunications: 'comingsoon13.md'
  - Cross-industry Accelerators: 
    - Sustainability: 'comingsoon14.md'
    - Data & AI Cross-industry: 'comingsoon15.md'
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom