site_name: AWS Partner Network (APN) Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints:
    - Advertising & Marketing:
      - Audience and Customer Data Management: 'Advertising&Marketing/AudienceAndCustomerDataManagement/AudienceAndCustomerDataManagement.md'
      - Advertising Platforms: 'Advertising&Marketing/AdvertisingPlatforms/AdvertisingPlatforms.md'
      - Advertising Intelligence and Measurement: 'Advertising&Marketing/AdvertisingIntelligenceAndMeasurement/AdvertisingIntelligenceAndMeasurement.md'
      - Privacy Enhanced Data Collaboration: 'Advertising&Marketing/Privacy Enhanced Data Collaboration/PrivacyEnhancedDataCollaboration.md'
    - Automotive: 'Automotive/comingsoon.md'
    - Aerospace & Satelite: 'comingsoon2.md'
    - Consumer Goods: 'comingsoon3.md'
    - Energy & Utilities:
      - Power & Utilities: 'Energy&Utilities/Power&Utilities/Power&Utilities.md'
      - Oil and Gas: 'Energy&Utilities/Oil&Gas/Oil&Gas.md'
    - Financial Services:
      - Core Banking System Modernization:
        - EKS Blueprints (CDK): 'https://aws-quickstart.github.io/cdk-eks-blueprints/'
        - Application Modernization Blueprints: 'https://catalog.us-east-1.prod.workshops.aws/workshops/96f22c5f-744f-46a6-9a98-a8b65941f85f/en-US'
    - Healthcare & Life Sciences: 'comingsoon6.md'
    - Manufacturing & Industrial: 'comingsoon7.md'
    - Media & Entertainment: 'comingsoon8.md'
    - Public Sector: 'comingsoon9.md'
    - Retail: 'comingsoon10.md'
    - Sports: 'comingsoon11.md'
    - Travel & Hospitality: 'comingsoon12.md'
    - Telecommunications: 'comingsoon13.md'
  - Cross-industry Accelerators: 
    - Sustainability:
      - Carbon Accounting: 'https://aws.amazon.com/solutions/guidance/sustainability-insights-framework-on-aws/?did=sl_card&trk=sl_card'
      - ESG Reporting & Disclosures: 'https://github.com/aws-solutions-library-samples/guidance-for-querying-sustainability-documents-using-generative-ai-for-esg-reporting-on-aws'
      - Product Carbon Footprint (PCF): 
        - Guidance for Environmental Impact Factor Mapping on AWS: 'https://aws.amazon.com/solutions/guidance/environmental-impact-factor-mapping-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Product Carbon Footprinting on AWS: 'https://aws.amazon.com/solutions/guidance/product-carbon-footprinting-on-aws/?did=sl_card&trk=sl_card'
      - Battery Performance Management: 'https://aws.amazon.com/solutions/guidance/electric-vehicle-battery-health-prediction-on-aws/?did=sl_card&trk=sl_card'
      - Renewable Energy Transition: 'https://aws.amazon.com/solutions/guidance/renewables-data-lake-and-analytics-on-aws/?did=sl_card&trk=sl_card'
      - Physical Climate Risk Assessment: 'https://aws.amazon.com/solutions/guidance/physical-climate-risk-assessment-on-aws/?did=sl_card&trk=sl_card'
      - Energy Use Optimization: 'https://aws.amazon.com/solutions/guidance/monitoring-and-optimizing-energy-usage-on-aws/?did=sl_card&trk=sl_card'
      - Sustainable Buildings:
        - Guidance for Smart and Sustainable Buildings on AWS: 'https://aws.amazon.com/solutions/guidance/smart-and-sustainable-buildings-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Monitoring and Optimizing Energy Usage on AWS: 'https://aws.amazon.com/solutions/guidance/monitoring-and-optimizing-energy-usage-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Utility Bill Processing on AWS: 'https://aws.amazon.com/solutions/guidance/utility-bill-processing-on-aws/?did=sl_card&trk=sl_card'
      - Water Stewardship:
        - Guidance for Water Use Efficiency on AWS: 'https://aws.amazon.com/solutions/guidance/water-use-efficiency-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Utility Bill Processing on AWS: 'https://aws.amazon.com/solutions/guidance/utility-bill-processing-on-aws/?did=sl_card&trk=sl_card'
      - Value Chain Transparency:
        - Guidance for Product Traceability on AWS: 'https://aws.amazon.com/solutions/guidance/product-traceability-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Geospatial Insights for Sustainability on AWS: 'https://aws.amazon.com/solutions/guidance/geospatial-insights-for-sustainability-on-aws/?did=sl_card&trk=sl_card'
      - Sustainable IT:
        - Guidance for Optimizing MLOps for Sustainability on AWS: 'https://aws.amazon.com/solutions/guidance/optimizing-mlops-for-sustainability-on-aws/?did=sl_card&trk=sl_card'
        - Guidance for Optimizing Deep Learning Workloads for Sustainability on AWS: 'https://aws.amazon.com/solutions/guidance/optimizing-deep-learning-workloads-for-sustainability-on-aws/'
        - Guidance for Optimizing Data Architecture for Sustainability on AWS: 'https://aws.amazon.com/solutions/guidance/optimizing-data-architecture-for-sustainability-on-aws/?did=sl_card&trk=sl_card'
    - Data & AI Cross-industry: 'comingsoon15.md'
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom