site_name: APN Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints:
    - Advertising & Marketing:
      - Customer360: 'https://github.com/aws-samples/aws-industry-blueprints-for-data-and-ai/tree/main/blueprints/datalake-warehouse-c360'
    - Automotive: 'comingsoon1.md'
    - Aerospace & Satelite: 'comingsoon2.md'
    - Consumer Goods: 'comingsoon3.md'
    - Energy & Utilities: 'comingsoon4.md'
    - Financial Services: 'comingsoon5.md'
    - Healthcare & Life Sciences: 'comingsoon6.md'
    - Manufacturing & Industrial: 'comingsoon7.md'
    - Media & Entertainment: 'comingsoon8.md'
    - Public Sector: 'comingsoon9.md'
    - Retail: 'comingsoon10.md'
    - Sports: 'comingsoon11.md'
    - Travel & Hospitality: 'comingsoon12.md'
    - Telecommunications: 'comingsoon13.md'
  - Cross-industry Accelerators: 
    - Sustainability: 'comingsoon14.md'
    - Data & AI Cross-industry: 'comingsoon15.md'
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom