site_name: APN Blueprints for Industry Solutions
docs_dir: docs/

theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Componentized Mechanism: 'components.md'
  - Core Concepts: 'core_concepts.md'
  - Industry Blueprints: 'comingsoon.md'
    - Advertising & Marketing:
      - Customer 360: 'https://github.com/aws-samples/aws-industry-blueprints-for-data-and-ai/tree/main/blueprints/datalake-warehouse-c360'
      - Campaigns and Journeys: 'https://github.com/aws-samples/communication-developer-services-reference-architectures'
      - Customer and User Support: 'comingsoon.md'
      - Digital Content Creation: 'comingsoon.md'
      - Retail Media: 'comingsoon.md'
      - Agency Enablement: 'comingsoon.md'
      - Measurement, Attribution and Verification: 'comingsoon.md'
      - Consent management & data governance in AdTech: 'comingsoon.md'
      - Data Cleanrooms: 'comingsoon.md'
    - Automotive: 'comingsoon.md'
    - Aerospace & Satelite: 'comingsoon.md'
    - Consumer Goods: 'comingsoon.md'
    - Energy & Utilities: 'comingsoon.md'
    - Financial Services: 'comingsoon.md'
    - Healthcare & Life Sciences: 'comingsoon.md'
    - Manufacturing & Industrial: 'comingsoon.md'
    - Media & Entertainment: 'comingsoon.md'
    - Public Sector: 'comingsoon.md'
    - Retail: 'comingsoon.md'
    - Sports: 'comingsoon.md'
    - Travel & Hospitality: 'comingsoon.md'
    - Telecommunications: 'comingsoon.md'
  - Cross-industry Accelerators: 'comingsoon.md'
    - Sustainability: 'comingsoon.md'
    - Data & AI Cross-industry: 'comingsoon.md'
  - Trainings: 'trainings.md'
  - Component request: 'request.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom